repos:
- repo: https://github.com/python/black
  rev: stable
  hooks:
  - id: black
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md, --markdown-linebreak-ext=Rmd]
